### ISSUE TITLE
Unzip required

### ISSUE THREAD

**Issue by dummai** [si-medbif/exomeseq#4]
Please add zip/unzip package to the requirement list to be installed before running the pipieline

**Comment by haraldgrove** [comment]
You're also going to need bgzip / tabix. Do you think there is any issue with having the users install these via "apt install"?

**Comment by dummai** [comment]
In DigitalOcean, you will need to do the following commands before running the pipeline:

apt update
apt install docker.io
apt install unzip

I think you should add 'Unzip' or other file compression program in the requirement. Is 'unzip' is in build-essential?

**Comment by dummai** [comment]
Also require:
apt install tabix

**Comment by haraldgrove** [comment]
I'll add it as a requirement for now, unzip, tabix and bgzip.

**Comment by dummai** [comment]
That should solve the problem
